---

- name: create opt directory for prometheus 
  file: 
    path: /opt/prometheus 
    state: directory

- name: create /var/log/prometheus directory
  file:
    path: /var/log/prometheus
    state: directory

- name: create var log promjobs directory
  file:
    path: /var/log/promjob
    state: directory

- name: unarchive node exporter
  unarchive:
    remote_src: yes
    src: '{{ repo_url }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz'
    dest: /opt/prometheus

- name: Install Node exporter init file
  template:
    src: node_exporter.j2
    dest: /etc/init.d/node_exporter
    mode: 0755

- name: Creating the log rotation for the node exporter logs
  copy:
    src: files/node_exporter_logrotate
    dest: /etc/logrotate.d/prom_exporters
    mode: 0755

- name: start node_exporter
  service:
    name: node_exporter
    state: restarted
  become_user: root

