---

# USAGE : ansible-playbook -i "$HOSTS," -e "user=$USER" redis_exporter.yml
# Example : ansible-playbook -i "10.0.0.61," -e "user=fooUser" redis_exporter.yml

 - name: Include all hosts
   hosts: all
   become: yes
   become_method: sudo
   user: '{{ user }}'
   gather_facts: no
   roles:
    - prometheus_redis_exporter 
